### ISSUE TITLE
Visual Studio for Mac 2019 error

### ISSUE THREAD

**Issue by mchambers101** [straighteight/SpecFlow-VS-Mac-Integration#21]
Hi,

Getting Error CS0234: 
The type or namespace name 'TestFixtureTearDownAttributeAttribute' does not exist in the namespace 'NUnit.Framework' (are you missing an assembly reference?) (CS0234) 
Updated everything to the latest version 
VS Version 8.0.2
SpecFlow Version 3.0.199
Straight8's SpecFlow Version 1.11.3.0
Mono Version 5.18.1.3.

Can you help please?

**Comment by mikeyjones** [comment]
Hi,

I believe the problem you're having is due to the backing .cs file that SpecFlow created was for SpecFlow v2+, which has a dependency on NUnit v2, but you are running the specs against NUnit v3. The code SpecFlow generates for Nuint v2 is not compatible with v3.

You need to get Visual Studio to run the custom tool again, I think if you if you edit the feature file and resave it, it should get Visual Studio to rerun the custom tool and generate an NUnit v3 backing .cs file. If that fails, try deleting the .feature file and create a new file within VS 2019.

Let me know if that works? As I managed to get this error when I played around on VS 2019 for Windows and SpecFlow v3, but I haven't been able to get VS 2019 for mac to do it for me, so I'm not sure if the same technique works.

**Comment by mchambers101** [comment]
Hi,

Thanks for the quick reply.

Ye i had to regenerate all my .cs files to get it to work.

Thanks
